# Site configuration
repository: FelixSaville/felixsaville.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Felix Saville
title: Systems Engineer
email: savillefelix2@gmail.com
website: https://felixsaville.github.io/

# Dark Mode configuration
darkmode: true

# Social links configuration
github_username: FelixSaville
facebook_username: FelixSaville
instagram_username: felix_saville
linkedin_username: felixsaville

# About Section configuration
about_content: |
  Hello there! I'm Felix, a Systems Engineer at OmniNet Limited with over 6 years of hands-on experience in IT infrastructure, automation, and cloud transitions.
  My expertise includes <mark>PowerShell automation</mark>, <mark>Microsoft 365 and Azure deployments</mark>, <mark>Intune and Autopilot device provisioning</mark>, and <mark>hybrid-to-cloud migrations</mark>. I specialize in streamlining IT operations across education, business, and corporate environments by developing scalable, efficient, and secure systems.
  At OmniNet, I lead client-focused IT projects ranging from Exchange migrations and cross-tenant consolidation to endpoint policy enforcement, compliance hardening, and platform automation. My scripting work enables consistency and control across complex environments.
  Outside of work, I continuously explore new technologies—from Linux optimization to cloud-native hosting—always sharpening my skills and pushing for smarter, more effective solutions.

# Main content configuration
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: OmniNet Limited
        link: https://www.omninet.co.nz/
        sub_title: Systems Engineer
        caption: July 2024 - Present
        quote: "Driving innovation and efficiency through cloud-first IT solutions."
        description: |
          Responsible for designing, implementing, and supporting IT infrastructure solutions across client environments. This includes Azure AD migrations, Microsoft 365 deployments, Intune/Autopilot device management, and endpoint security configurations. Acted as a technical lead on projects involving cloud-first strategies, hybrid infrastructure transitions, and client onboarding, while providing escalation support and maintaining strong client relationships.
      - layout: left
        title: mb3 Limited
        link: https://www.mb3.nz/
        sub_title: Systems Engineer
        caption: March 2022 - July 2024
        quote: "Enriching lives using Apple technology. Inspire, Innovate, Empower."
        description: |
          I joined mb3 Limited as a Systems Engineer, specializing in the management and deployment of IT systems within Microsoft, Linux, and Apple ecosystems. My primary focus was to enhance IT system manageability and streamline device deployment for iwi, education, and business. My key responsibilities included the design and execution of IT projects, optimizing operations through automation, and overseeing helpdesk requests. In my role, I was committed to delivering high-quality support across various solutions, ensuring that our clients' IT ecosystems were both efficient and user-friendly.
      - layout: left
        title: Timberlands Limited
        link: https://tll.co.nz/
        sub_title: IT Support Specialist
        caption: October 2019 - March 2022
        quote: "We commit to being the best and safest production forest in the world, Mo ake tonu atu."
        description: |
          Originally joined Timberlands as an IT Support Specialist, rapidly learning the organization's IT infrastructure, focusing on optimizing day-to-day operations. Key accomplishments include mastering the complex platform Citrix, private cloud structure, enhancing control and support for the IT team and staff, and providing exceptional support to users, both on-site and remotely, while maintaining efficiency and user satisfaction.
      - layout: left
        title: Spark Rotorua
        link: https://www.spark.co.nz/
        sub_title: Sales Consultant
        caption: November 2018 - March 2019
        quote: "The best hands-on experience is front-facing all types of customers, assisting NZ in the digital world."
        description: |
          At Spark, a leader in telecommunications and digital services, provided support to customers as a Sales Consultant. Responsibilities/achievements included providing detailed consults on devices and digital services to many customers across NZ, finding effective and accurate solutions while providing excellent customer support, and greatly exceeding sales targets by selling 60 solutions within a single month.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Avonmore / EmployNZ
        caption: February 2016 - November 2018
        sub_title: Diploma in Systems Administration (Level 6)
        quote: "EmployNZ helped me learn a lot around System Deployment and Management, and I couldn’t have done IT without their Hands-On Teaching."
        description: |
          During my time at EmployNZ, I learnt most of my key skills that I have taken through my career, such as teamwork and working to tight deadlines. I thoroughly enjoyed my time at EmployNZ and learnt a lot about different Types of Operating Systems, platforms, and programming Languages.

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Company-Wide Laptop Rollout
        quote: "July 2021 - December 2021"
        description: |
          Took on a laptop rollout to support Timberlands' transition to remote work during challenges such as chip shortages and global pandemic-related delays. Managed all aspects of the rollout, including procurement, cybersecurity training, deployment, and helpdesk support. This project allowed me to execute complex IT initiatives under pressure, ensuring business continuity and enhancing remote work capabilities.
      - layout: top-middle
        title: Private-Cloud Deployment
        quote: "May 2022 - August 2022"
        description: |
          Deployed and configured a full Proxmox VE-based infrastructure using clustered local hardware to host a private cloud. This strategic environment supported critical in-house applications, including Bitwarden, Bookstack Wiki, and various virtual machines. The project demonstrated my proficiency in virtualization technologies by delivering a resilient, scalable, and secure cluster.
      - layout: top-middle
        title: Cloud Platform Automations
        quote: "June 2022 - June 2024"
        description: |
          Successfully developed and maintained an advanced automation framework using PowerShell, designed to synchronize user account operations between Microsoft 365, Google Workspace, and Apple School Manager. Integrated with school SMS platforms to streamline account creation, licensing, and group assignments. Improved operational efficiency and platform reliability across education clients.
      - layout: top-middle
        title: VoIP Deployment
        quote: "September 2022 - April 2024"
        description: |
          Deployed and configured various VoIP platforms across educational and corporate clients in the Bay of Plenty region. Implemented solutions such as Webex, Microsoft Teams, and UCXpress through Access 4. Gained expertise in VoIP systems while enhancing client communication infrastructure and collaboration capabilities.
      - layout: top-middle
        title: Cross-Tenant Microsoft 365 Migration
        quote: "August 2024 – September 2024"
        description: |
          Constructed a Microsoft 365 tenant-to-tenant migration using AvePoint Fly. Consolidated user mailboxes and calendars, developed PowerShell automation to replicate permissions and calendar delegations, and coordinated DNS cutovers. Delivered a seamless migration experience with minimal downtime and configuration impact.
      - layout: top-middle
        title: Autopilot Deployment Project
        quote: "May 2025 - June 2025"
        description: |
          Designed and implemented a modern device deployment and management strategy using Microsoft Intune and Autopilot. This included a 35-device deployment, Win32 app packaging, Defender configuration, and conditional access policies. Delivered standardized deployment templates and automation for Start Menu layouts, Taskbar pinning, and Office provisioning across multiple clients.

# Footer configuration
footer_show_references: true
references_title: Email me directly for more information and references!

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

seo:
  name: Felix Saville
  description: "Felix Saville – Systems Engineer specializing in cloud infrastructure, automation, and device deployment."
