# Site configuration
repository: FelixSaville/felixsaville.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Felix Saville
title: Systems Administrator
email: savillefelix2@gmail.com
website: https://felixsaville.github.io/

# Dark Mode configuration
darkmode: true

# Social links configuration
github_username: FelixSaville
facebook_username: FelixSaville
instagram_username: felix_saville
linkedin_username: felixsaville

# About Section configuration
about_content: |
  Hello there! I'm Felix, a Systems Engineer at OmniNet Limited, bringing over 6 years of experience to the ever-evolving world of Information Technology.
  My experience spans <mark>Automation Development (PowerShell, Rust API, Python)</mark>, <mark>Website Design (PHP, JavaScript, HTML + CSS)</mark>, <mark>Infrastructure Management (On-Site, Azure, Google, Hybrid)</mark>, and <mark>Device Deployment (JAMF, Intune, Autopilot)</mark>.
  At OmniNet, I design and implement IT infrastructure solutions, lead cloud-first and hybrid projects, and deliver automation to streamline operations. My technical skills are complemented by strong client management, professional communication, and a passion for simplifying complex system problems.
  My dedication to technology extends beyond work hours—I'm always exploring the latest trends, fueling my continuous growth in IT.

# Main content configuration
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: OmniNet Limited
        link: https://www.omninet.co.nz/
        sub_title: Systems Engineer
        caption: July 2024 - Present
        quote: "Driving innovation and efficiency through cloud-first IT solutions."
        description: |
          Responsible for designing, implementing, and supporting IT infrastructure solutions across client environments. This includes Azure AD migrations, Microsoft 365 deployments, Intune/Autopilot device management, and endpoint security configurations. Acted as a technical lead on projects involving cloud-first strategies, hybrid infrastructure transitions, and client onboarding, while providing escalation support and maintaining strong client relationships.
      - layout: left
        title: mb3 Limited
        link: https://www.mb3.nz/
        sub_title: Systems Engineer
        caption: March 2022 - July 2024
        quote: "Enriching lives using Apple technology. Inspire, Innovate, Empower."
        description: |
          I joined mb3 Limited as a Systems Engineer, specializing in the management and deployment of IT systems within Microsoft, Linux, and Apple ecosystems. My primary focus was to enhance IT system manageability and streamline device deployment for iwi, education, and business. My key responsibilities included the design and execution of IT projects, optimizing operations through automation, and overseeing helpdesk requests. In my role, I was committed to delivering high-quality support across various solutions, ensuring that our clients' IT ecosystems were both efficient and user-friendly.
      - layout: left
        title: Timberlands Limited
        link: https://tll.co.nz/
        sub_title: IT Support Specialist
        caption: October 2019 - March 2022
        quote: "We commit to being the best and safest production forest in the world, Mo ake tonu atu."
        description: |
          Originally joined Timberlands as an IT Support Specialist, rapidly learning the organization's IT infrastructure, focusing on optimizing day-to-day operations. Key accomplishments include mastering the complex platform Citrix, private cloud structure, enhancing control and support for the IT team and staff, and providing exceptional support to users, both on-site and remotely, while maintaining efficiency and user satisfaction.
      - layout: left
        title: Spark Rotorua
        link: https://www.spark.co.nz/
        sub_title: Sales Consultant
        caption: November 2018 - March 2019
        quote: "The best hands-on experience is front-facing all types of customers, assisting NZ in the digital world."
        description: |
          At Spark, a leader in telecommunications and digital services, provided support to customers as a Sales Consultant. Responsibilities/achievements included providing detailed consults on devices and digital services to many customers across NZ, finding effective and accurate solutions while providing excellent customer support, and greatly exceeding sales targets by selling 60 solutions within a single month.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Avonmore / EmployNZ
        caption: February 2016 - November 2018
        sub_title: Diploma in Systems Administration (Level 6)
        quote: "EmployNZ helped me learn a lot around System Deployment and Management, and I couldn't of done IT without their Hands-On Teaching."
        description: |
          During my time at EmployNZ, I learnt most of my key skills that I have taken through my career, such as teamwork and working to tight deadlines. I thoroughly enjoyed my time at EmployNZ and learnt a lot about different Types of Operating Systems, platforms, and programming Languages.

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Timberlands Website Rebuild
        quote: "March 2020 - June 2020"
        description: |
          Led a strategic in-house rebuild of the Timberlands website as part of my KPI's, transforming it into a cost-effective, self-managed platform. Collaborated closely with a colleague to enhance user experience, utilizing Drupal on an on-site Virtual Machine. Focused on developing a user-friendly GUI for both visitors and editors, ensuring accessibility and efficiency.
      - layout: top-middle
        title: Asset Management System Implementation
        quote: "May 2021 - July 2021"
        description: |
          Led the introduction of an asset management system at Timberlands, conducting a cost-benefit analysis to secure managerial support. Selected and implemented SNIPE-IT, a robust, open-source solution tailored for IT teams. This project allowed me to perfect my technical expertise in PHP, Java, CSS, and REST APIs, significantly enhancing digital asset management and future IT support capabilities.
      - layout: top-middle
        title: Company-Wide Laptop Rollout
        quote: "July 2021 - December 2021"
        description: |
          Took on a laptop rollout to support Timberlands' transition to remote work during challenges such as chip shortages and global pandemic-related delays. Managed all aspects of the rollout, including procurement, cybersecurity training, deployment, and helpdesk support. This project allowed me to execute complex IT initiatives under pressure, ensuring business continuity and enhancing remote work capabilities.
      - layout: top-middle
        title: Private-Cloud Deployment
        quote: "May 2022 - July 2022"
        description: |
          Deployment and configuration of a full Proxmox VE-Based infrastructure by utilizing clustered local hardware to deploy a private cloud. This strategic plan was aimed at hosting a suite of critical in-house applications, including Bitwarden, Bookstack Wiki and various VM's. This project displayed my knowledge in VM technology to design a high-resistant, scalable and secure cluster environment.
      - layout: top-middle
        title: Cloud Platform Automations
        quote: "June 2022 - Ongoing"
        description: |
          Successfully developed and implemented an advanced automation framework using PowerShell, designed to synchronize user account operations between Microsoft, Google, and Apple School Manager. Using data from schools' SMS platforms, these automations enhanced inter-platform connectivity, streamlined account management, and displayed my adaptive and deep understanding of PowerShell. This project allowed for massive operational efficiency for clients and reliability of our services.
      - layout: top-middle
        title: VoIP Deployment
        quote: "September 2022 - Ongoing"
        description: |
          Deployed and configured a VoIP platform across a range of educational/corporate clients within the Bay Of Plenty Region, using cutting-edge VoIP solutions like Webex, Microsoft Teams, and UCXpress through Access 4. This deployment allowed me to learn VoIP technology and adapt these skill sets into existing environments, allowing for organizational collaboration platforms and connectivity for our clients.

# Footer configuration
footer_show_references: true
references_title: Email me directly for more information and references!

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

seo:
  name: Felix Saville
  description: "Felix Saville - Experienced Systems Administrator specializing in automation, infrastructure management, and cloud technologies."
